#! /usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'
script_dir=$(cd $( dirname "${BASH_SOURCE[0]}" ) && pwd)
cd "$script_dir"
. ./tools/bash-common

usage() {
  echo "Usage: $0"
  echo
  echo "This script builds the code for an environment, runs the database migrations,"
  echo "commits the code, pushes it to github, and pushes it to elastic beanstalk."
  echo
  exit 1
}
show_help "${1:-}"

banner "MTG build"

current_date=$(date)
current_branch=$(git rev-parse --abbrev-ref HEAD)
current_commit=$(git rev-parse HEAD)
eb_env=andywhite37-mtg

check_git_status

# Make sure dependencies are up-to-date with hmm.json
#run_command "hmm check || exit 1"

banner "MTG elastic beanstalk deployment"

echo "$USER - $current_date - $current_branch (${current_commit}) -> $eb_env" >> "./logs/deploy.${eb_env}.log"
confirm_ok "This will commit the app code, push it to github branch $current_branch, and push it to elastic beanstalk env: $eb_env"

banner "Push to github"
run_command "git add -A ."
run_command "git commit -m 'Deployment: $eb_env - $USER - $current_date'"
run_command "git push origin $current_branch"

banner "Push to elastic beanstalk"
run_command "eb deploy $eb_env"

run_command "./migrate"
