#!/usr/bin/env node
var _ = require('lodash');
var Promise = require('bluebird');
var chalk = require('chalk');
var fs = require('fs');
var path = require('path');
var pgb = require('pg-bluebird');
var request = require('request');
Promise.promisifyAll(request);

var sets = JSON.parse(fs.readFileSync(path.join(__dirname, 'AllSets-x.json'), 'utf-8'));
var setCodes = _.keys(sets);
var firstSetCode = setCodes[0];
var firstSet = sets[firstSetCode];
var cards = firstSet.cards;
var card = cards[0];

card.types = card.types || [];
card.releaseDate = card.releaseDate || firstSet.releaseDate;
card.names = card.names || [card.name];

console.log(card);

request.postAsync({
  url: 'http://localhost:9999/api/cards',
  body: card,
  json: true
})
.spread(function(response, body) {
  console.log(body);
})
.catch(function(err) {
  console.error(chalk.red('error'));
  console.error(err);
});
