package mtg.client.api;

import js.jquery.JqXHR;

typedef JQueryAjaxOptions = {
  ?accepts: Dynamic,
  ?async : Bool,
  ?beforeSend: JqXHR -> Dynamic -> Void,
  ?cache : Bool,
  ?complete: JqXHR -> String -> Void,
  ?contents : Dynamic,
  ?contentType: String,
  ?context : Dynamic,
  ?converters : Dynamic,
  ?crossDomain : Bool,
  ?data : Dynamic,
  ?dataFilter : String -> String -> Dynamic,
  ?dataType : String,
  ?error : JqXHR -> String -> String -> Void,
  ?global : Bool,
  ?headers : Dynamic,
  ?ifModified : Bool,
  ?isLocal : Bool,
  ?jsonp : String,
  ?jsonpCallback : Dynamic,
  ?mimeType : String,
  ?password : String,
  ?processData : Bool,
  ?scriptCharset : String,
  ?statusCode : Dynamic,
  ?success : Dynamic -> String -> JqXHR -> Void,
  ?timeout: Int,
  ?traditional : Bool,
  ?type : String,
  ?url : String,
  ?username : String,
  ?xhr : Void -> Dynamic,
  ?xhrFields : Dynamic,
};
