#!/usr/bin/env node

var chalk = require('chalk');
var path = require('path');
var postgrator = require('postgrator');

var config = {
  migrationDirectory: path.join(__dirname, '..', 'migrations'),
  schemaTable: '_schema_version',
  driver: 'pg',
  host: process.env.DATABASE_HOST || 'localhost',
  database: process.env.DATABASE_NAME || 'mtg',
  username: process.env.DATABASE_USERNAME || '',
  password: process.env.DATABASE_PASSWORD || ''
};

postgrator.setConfig(config);

postgrator.migrate('max', function (err, migrations) {
  if (err) {
    console.log(chalk.red('migrations failed'));
    console.error(err);
  } else {
    //console.log(migrations);
    console.log(chalk.green('migrations ran successfully'));
  }

  postgrator.endConnection(function () {
    console.log(chalk.green('connection to database closed successfully'));
  });
});
